### ISSUE TITLE
compiling doesn't work, eth driver missing

### ISSUE THREAD

**Issue by MartinNPN** [espressif/esp32-quake#2]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [X] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [X] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

The code should compile.

### Actual behavior (suspected bug)

The code has problems at compiling, the generic eth driver seems wrong.

### Error logs or terminal output

```shell
C:/.../.espressif/tools/riscv32-esp-elf/esp-13.2.0_20240530/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld.exe: esp-idf/main/libmain.a(eth_connect.c.obj): in function `eth_init_internal':
C:/.../esp32-quake/main/eth_connect.c:53:(.text.ethernet_connect+0x8e): undefined reference to `esp_eth_phy_new_generic'      
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

### Steps to reproduce the behavior

Checkout project, import in VS Code and hit compile.

### Project release version

latest

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Windows

### Operating system version

Windows 11

### Shell

PowerShell

### Additional context

i used esp idf 5.3.1

**Comment by MartinNPN** [comment]
I just found the solution myself, using the ESP IDF master branch solves the issue, but this means that the comment "This project needs ESP-IDF v5.3 or later to properly compile" is missleading, this should be changed.

**Comment by Spritetm** [comment]
Thanks, I think I may have changed to master somewhere along the way as I also develop on ESP-IDF itself once in a while. I'll either backport it or change the readme when I have some time.
